server {
    listen 80;
    server_name _;
    root /usr/share/nginx/html;
    index index.html;

    location /api/ {
        proxy_pass http://request-media:9380;
        proxy_http_version 1.1;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    location /images/movies/ {
        proxy_pass http://media-movies:9430/images/;
        proxy_http_version 1.1;
        proxy_set_header Host $host;
    }

    location /images/tv/ {
        proxy_pass http://media-tvshows:9450/images/;
        proxy_http_version 1.1;
        proxy_set_header Host $host;
    }

    location /stream/ {
        proxy_pass http://media-movies:9430;
        proxy_http_version 1.1;
        proxy_set_header Host $host;
    }

    location / {
        try_files $uri $uri/ /index.html;
    }
}
